### ISSUE TITLE
Implement wireguard storage as a json file

### ISSUE THREAD

**Issue by clly** [clly/wireguard-cni#53]
Currently all wireguard public keys and what they belong to is held completely in memory. We need to start storing the data so that we can persist everything across process restarts.

We can do this at the same time we make an edit to the map and then persist it to a file.

**Comment by ksankeerth** [comment]
Hi @clly,
wirecard-cni seems to be interesting. I'm learning linux networking from the open source. Can I try to fix this issue?

**Comment by clly** [comment]
Sure! I've already done persistence here: https://github.com/clly/wireguard-cni/pull/59 but we still need to ensure that it's loaded from the file on startup.

If you might be more interested in something a little bigger let me know and I can break down one of the larger issues into smaller tasks.

**Comment by ksankeerth** [comment]
@clly thanks.I had a quick look at the code. As far as I understand, currently, ADD of CNI has been implemented. When ADD command is executed, It'll connect to the node manager server and add an interface and allocate an IP address. 

I think currently cluster-manager nor node-manager don't start with `opt  WithDataDir(d string) .  Do you expect to store JSON data for node-manager and cluster manager in any specific path?

[Cluster manager](https://github.com/clly/wireguard-cni/blob/main/cmd/cluster-manager/main.go#L30)
[Node manager](https://github.com/clly/wireguard-cni/blob/main/cmd/node-manager/svr.go#L84)

Sure, I can give it a try on working something bigger

**Comment by clly** [comment]
:+1: If you're ok with half of this done that's fine :) just wanted to make sure. 

Cluster-manager and node-manager don't use the `WithDataDir` option yet. I didn't have plans to store the data in a specific path yet but something inside the current working directory would be fine to start out with.

**Comment by ksankeerth** [comment]
@clly No worries. If you are going to work on that, that's better too. I just checked the code to understand how you have implemented CNI using wire-guard.  If you need help on any other issues, I'm happy to take it 🙂

**Comment by clly** [comment]
I think that this would be a great issue for you to start with and then we can keep moving forward to other issues?

If this is something you want to work on that would be great.
